name: Build & Dockerize Spring Boot App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-docker:
    runs-on: ubuntu-latest

    steps:
      #  Clonar el repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Construir el proyecto con Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      #  Login a Docker Hub usando secretos
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t danyflores97/backend:latest .

      # Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push danyflores97/backend:latest
